host:
  host_type: # APACHE | NGINX | CADDY | RAPSCALLION | CUSTOM
  root_url: ""

  sections:
    - section_name: ""
      host_subdirectory: ""
      local_directory: ""

  table_columns:
    filename_header: ""
    file_size_header: ""
    date_header: ""

  source_replacements:
    "]]": "]]"

  filters:
    - ""

show_item_count: false
