name: Package Mortar

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Build with Dockerfile (matching bullseye environment)
        run: |
          docker buildx build --platform linux/arm64 -t retro-console-arm64 -f Dockerfile .
          docker create --name extract retro-console-arm64
          docker cp extract:/build/mortar mortar
          docker rm extract

      - name: Build Package Folder
        run: |
          mkdir Mortar.pak
          cp -R mortar launch.sh README.md LICENSE pak.json resources/setup-qr.png fonts Mortar.pak

      - uses: actions/upload-artifact@v4
        with:
          name: Mortar.pak
          path: Mortar.pak
          if-no-files-found: error
          retention-days: 3
          overwrite: true