name: Package Mortar

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            libsdl2-dev \
            libsdl2-ttf-dev \
            libsdl2-image-dev

      - name: Build
        run: env GOOS=linux GOARCH=arm64 go build -o mortar .

      - name: Build Package Folder
        run: |
          mkdir Mortar.pak
          cp -R mortar launch.sh README.md LICENSE pak.json resources/setup-qr.png Mortar.pak

      - uses: actions/upload-artifact@v4
        with:
          name: Mortar.pak
          path: Mortar.pak
          if-no-files-found: error
          retention-days: 3
          overwrite: true