name: Package Mortar

on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:

  build:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Build with Dockerfile (matching bullseye environment)
        run: |
          docker buildx build --platform linux/arm64 -t retro-console-arm64 -f Dockerfile .
          docker create --name extract retro-console-arm64
          docker cp extract:/build/mortar mortar
          docker rm extract

      - name: Build Package Folder
        run: |
          mkdir Mortar.pak
          cp -R mortar launch.sh README.md LICENSE pak.json resources data Mortar.pak

      - uses: actions/upload-artifact@v4
        with:
          name: Mortar.pak
          path: Mortar.pak
          if-no-files-found: error
          retention-days: 3
          overwrite: true